version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - export NORMAL_BRANCH=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed 's/branch\///' | sed 's/pr\///')
      - pip install -qq -U pip wheel
      - pip install -r requirements.txt
      - pip install -r jbcli/requirements-dev.txt
      - pip install junit2html==30.0.6
      - mkdir /tmp/artifacts
      - flake8 --output-file=flake8_errors.txt --exit-zero jbcli
      - mv ./flake8_errors.txt /tmp/artifacts
      - cd jbcli
      - pytest --junit-xml=`pwd`/junit.xml --cov-branch --cov-report=xml:`pwd`/coverage.xml --cov=jbcli/cli -vvv
      - junit2html junit.xml || true
      - mv junit.xml.html coverage.xml /tmp/artifacts/
  build:
    commands:
      - make docs
      - |
        if [ "$NORMAL_BRANCH" = "master" ]; then
            aws s3 sync docs/_build/html s3://internal.juiceboxdata.com/projects/jbcli --acl bucket-owner-full-control --delete
        fi
artifacts:
  files:
    - /tmp/artifacts/* 
