version: '2'
services:
  juicebox:
    image: "423681189101.dkr.ecr.us-east-1.amazonaws.com/juicebox-devlandia:stable"
    command: bash -c "/venv/bin/python docker/entrypoint.py"
    ports:
      - "8000:8000"
      - "8888:8888"
      - "2222:22"
    depends_on:
      - "redis"
      - "postgres"
    volumes:
      - ./fruition/data:/code/data
      - ./fruition/dataservices:/code/dataservices
      - ./fruition/fruition:/code/fruition/
      - ./fruition/hashr:/code/hashr
      - ./fruition/invitation:/code/invitation
      - ./fruition/jbcommands:/code/jbcommands
      - ./fruition/metadata:/code/metadata
      - ./fruition/people:/code/people
      - ./fruition/public:/code/public
      - ./fruition/snapshots:/code/snapshots
      - ./fruition/stacks:/code/stacks
      - ./fruition/templates:/code/templates
      - ./fruition/themes:/code/themes
      - ./fruition/tours:/code/tours
      - ./apps:/code/apps
      - ~/.boto:/root/.boto:ro
    links:
      - postgres
      - redis
    environment:
      - ENVIRONMENT=docker
      - DJANGO_SETTINGS_MODULE=fruition.settings.docker
      - REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - APP_ID=1ec756a5-e04a-4885-87ad-3325bbdd4872
  postgres:
    environment:
      - POSTGRES_USER=juicebox
      - POSTGRES_PASSWORD=juicebox
      - POSTGRES_DB=juicebox
    image: "postgres:9.3-alpine"
  redis:
    image: "redis:2.8.6"
