version: '3.2'
services:
  juicebox:
    image: "423681189101.dkr.ecr.us-east-1.amazonaws.com/controlcenter-dev:dev-JB-1196_dockerize"
    command: bash -c "python docker/entrypoint.py"
    volumes:
      - ../../apps:/code/apps
      - ~/.boto:/root/.boto:ro
      - ~/.config/juicebox:/root/.config/juicebox:ro
    environment:
      - DJANGO_SETTINGS_MODULE=fruition.settings.docker
      - AWS_PROFILE=hstm
