version: '3.2'
services:
  juicebox:
    image: "423681189101.dkr.ecr.us-east-1.amazonaws.com/controlcenter-dev:dev-JB-1196_dockerize"
    command: bash -c "/venv/bin/pip install -U -q -r requirements.txt && /venv/bin/python docker/entrypoint.py"
    volumes:
      - ./hstm-juicebox:/code
      - ../../apps:/code/apps
      - ~/.aws:/root/.aws:ro
      - ~/.config/juicebox:/root/.config/juicebox:ro
    links:
      - loginproxy
    environment:
      - DJANGO_SETTINGS_MODULE=fruition.settings.docker
      - AWS_PROFILE=hstm
  loginproxy:
    image: "423681189101.dkr.ecr.us-east-1.amazonaws.com/hstm-loginproxy-devlandia:1.0"
    ports:
      - "8889:8889"
