version: '2'
services:
  juicebox:
    image: "423681189101.dkr.ecr.us-east-1.amazonaws.com/controlcenter-dev:dev-JB-1196_dockerize"
    command: bash -c "python docker/entrypoint.py"
    ports:
      - "8000:8000"
      - "8888:8888"
      - "2222:22"
    depends_on:
      - "redis"
      - "postgres"
    volumes:
      - ./hstm-juicebox/data:/code/data
      - ./hstm-juicebox/dataservices:/code/dataservices
      - ./hstm-juicebox/fruition:/code/hstm-juicebox/
      - ./hstm-juicebox/hashr:/code/hashr
      - ./hstm-juicebox/invitation:/code/invitation
      - ./hstm-juicebox/jbcommands:/code/jbcommands
      - ./hstm-juicebox/metadata:/code/metadata
      - ./hstm-juicebox/people:/code/people
      - ./hstm-juicebox/public:/code/public
      - ./hstm-juicebox/snapshots:/code/snapshots
      - ./hstm-juicebox/stacks:/code/stacks
      - ./hstm-juicebox/templates:/code/templates
      - ./hstm-juicebox/themes:/code/themes
      - ./hstm-juicebox/tours:/code/tours
      - ./apps:/code/apps
      - ~/.boto:/root/.boto:ro
    links:
      - postgres
      - redis
    environment:
      - ENVIRONMENT=docker
      - DJANGO_SETTINGS_MODULE=fruition.settings.docker
      - REGION=us-east-1
      - APP_ID=1ec756a5-e04a-4885-87ad-3325bbdd4872
  postgres:
    environment:
      - POSTGRES_USER=juicebox
      - POSTGRES_PASSWORD=juicebox
      - POSTGRES_DB=juicebox
    image: "postgres:9.3-alpine"
  redis:
    image: "redis:2.8.6"
